= Pflichtenheft
:project_name: Kleinreparaturbetrieb
:toc: macro
:toc-title:
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 4, 1"]
|===
|Version | Status      | Bearbeitungsdatum   | Autor(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2019          | _Template-Autor_       | Initiale Version
|1.0.0   | Fertig      | 3.11.2019           |
Till Große, Tobias Köllner, Anna Lopatkina, Kien Dang Tran, Viktor Reusch | Finale Version
|===

== Inhaltsverzeichnis

toc::[]
:numbered:

== Zusammenfassung
Dieses Dokument stellt die _Software Requirement Specification_ (SRS) von Miss-Mint-Filialmanagement dar.
Es liefert eine Übersicht über die zu bauende Software und fungiert als Basis für die Kommunikation zwischen den
Beteiligten dieses Projektes. Das Pflichtenheft beschreibt, was das gewünschte System zu erfüllen hat und
teilweise wie der Auftragnehmer die Lösung zu implementieren hat.

Die Spezifikationen sollen i.A. korrekt, vollständig und konsistent sein. Da sie am Ende des Projektes
genutzt werden um zu prüfen, ob die Software den Anforderungen enspricht.

== Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

Kleinreparaturbetrieb 
Jeder Miss-Mint-Reparaturbetrieb umfasst:

- eine Flickschusterei (Absätze, Sohlen, Nähte)
- einen Nähservice (Knöpfe, Nähte, Flicken)
- einen Schlüsseldienst (Schlüssel kopieren, Schilder gravieren)
- eine Schnellreinigung und Heißmangel (Wäsche, Anzüge, Leder)
- eine Elektrowerkstatt (Kabel ersetzen, löten)
- eine Scherenschleiferei (Scheren, Messer schärfen)

__Bestellung:__

- Unmittelbare Erfassung des Preises bei Annahme am Annahmeschalter + Vorauszahlung
- Auftragszettel für Kunden = (eindeutigen Auftragsnummer + Fertigstellungstermin)

__Abholung:__

- Vorlage des Auftragszettels

-  (0 - 7 Tage) = Abholungszeitraum 
-  3 Monate = Aufbewahrung + Lagergebühr (0,50€/7 Tage) 
-  danach = karitative Organisation

__Lieferverzögerung:__

- ab Fertigstellungstermin 10% Rabatt auf Reperaturkosten/Tag Verzögerung

__Softwareansprüche:__

- Annahme, Reparaturplanung, Ausgabe und Lagerung der Waren
- Ressourcenverwaltung  
- laufende und akkumulierte Bilanzen (monatliche Bilanz/Gesamtbilanz/evtl. tägliche Bilanz)  

__Aufgaben des Filialmanagments:__

- Bereitstellung der Ressourcen (Personal, Arbeitsgerät, Material, Räume)
- monatliche Abrechnung (Umsatz - Kosten = Gewinn) an Zentrale

include::produktnutzung.adoc[]

include::interessensgruppen.adoc[]

include::systemgrenze.adoc[]

include::anwendungsfälle.adoc[]

include::funktionale_anforderungen.adoc[]

include::nicht-funktionale_anforderungen.adoc[]

include::gui_prototyp.adoc[]

include::datenmodell.adoc[]

include::akzeptanztestfälle.adoc[]

== Glossar

////
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?
////

[cols="1, 4"]
|===
|Nutzer        |
Ein vom Admin autorisierter Mitarbeiterin bzw. eine autorisierte Mitarbeiterin,
der oder die sich im System ab- und anmelden kann.

|Mitarbeiter   |
Eine Mitarbeiterin bzw. ein Mitarbeiter der Firma. Dies kann ein Angestellter oder der Filialleiter sein.

|Admin         |
Hier wird angenommen, das dies der Filialleiter ist, der dann die höchsten Rechte im System hat.
Er übernimmt daher alle Verwaltungsaufgaben.
Diese Aufgabe kann aber natürlich auch ausgelagert werden.

|Salespoint    |
Java-basiertes Anwendungs-Framework zur Entwicklung von PoS-Anwendungen (Point of Sales)
mit Spring Framework und Spring Boot.
Es besteht aus einer Vielzahl von Geschäftsmodulen, die es den Benutzern ermöglichen,
anspruchsvolle Webanwendungen zu implementieren.
|===

////
== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
////
