= Pflichtenheft
:project_name: Kleinreparaturbetrieb
:toc: macro
:toc-title:
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 4, 1"]
|===
|Version | Status      | Bearbeitungsdatum   | Autor(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2019          | _Template-Autor_       | Initiale Version
|1.0.0   | Fertig      | 3.11.2019           |
Till Große, Tobias Köllner, Anna Lopatkina, Kien Dang Tran, Viktor Reusch | Finale Version
|===

== Inhaltsverzeichnis

toc::[]
:numbered:

== Zusammenfassung
Dieses Dokument stellt die _Software Requirement Specification_ (SRS) von Miss-Mint-Filialmanagement dar.
Es liefert eine Übersicht über die zu bauende Software und fungiert als Basis für die Kommunikation zwischen den
Beteiligten dieses Projektes. Das Pflichtenheft beschreibt, was das gewünschte System zu erfüllen hat und
teilweise wie der Auftragnehmer die Lösung zu implementieren hat.

Die Spezifikationen sollen i.A. korrekt, vollständig und konsistent sein. Da sie am Ende des Projektes
genutzt werden um zu prüfen, ob die Software den Anforderungen enspricht.

== Aufgabenstellung und Zielsetzung
////
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.
////

Es soll eine Software bereitgestellt werden für _Miss Mint Mending Points_. Dabei bezieht sich
die Software auf jeweils eine Filiale. Ein Kleinreparaturbetrieb umfasst:

- eine Flickschusterei (Absätze, Sohlen, Nähte)
- einen Nähservice (Knöpfe, Nähte, Flicken)
- einen Schlüsseldienst (Schlüssel kopieren, Schilder gravieren)
- eine Schnellreinigung und Heißmangel (Wäsche, Anzüge, Leder)
- eine Elektrowerkstatt (Kabel ersetzen, löten)
- eine Scherenschleiferei (Scheren, Messer schärfen)


__Bestellung:__

An den Annahmeschaltern wird die gewünschte Dienstleistung gewählt und der Kunde zahlt im Voraus.
Im Anschluss erhält der Kunde einen Auftragszettel, welcher eine eindeutige Identifikationsnummer und
einen Fertigstellungstermin beinhaltet.

__Abholung:__

Ab dem Fertigstellungstermin kann die Ware eine Woche lang unter Vorlage des Auftragszettels
abgeholt werden. Danach wandert die Ware für drei Monate in eine Aufbewahrungsstelle, wo sie unter
Vorlage des Auftragszettels durch eine Zahlung der Aufbewahrungsgebühr von 0,50€ pro Woche ausgelöst werden
kann. Falls die Ware in diesem Zeitraum nicht abgeholt wurde, wird sie an eine karitative Organisation
weitergegeben.

__Lieferverzögerung:__

Bei Lieferverzögerungen werden ab dem Fertigstellungstermin für jeden vollen Tag 10% Rabatt der Reparaturkosten erstattet
(maximal 100%).

__Softwareansprüche:__

Die Software soll sich um die Annahme, Reparaturplanung, Ausgabe und Lagerung der Waren kümmern.
Zusätzlich sollen Ressourcen wie Personal, Arbeitsgeräte, Materialien und Räume im System
verwaltbar sein. Die laufenden und akkumulierten Bilanzen sollen für den Filialleiter einsehbar sein.
Am Monatsende soll der monatliche Reingewinn an die Zentrale geschickt werden.

include::produktnutzung.adoc[]

include::interessensgruppen.adoc[]

include::systemgrenze.adoc[]

include::anwendungsfälle.adoc[]

include::funktionale_anforderungen.adoc[]

include::nicht-funktionale_anforderungen.adoc[]

include::gui_prototyp.adoc[]

include::datenmodell.adoc[]

include::akzeptanztestfälle.adoc[]

== Glossar

////
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?
////

[cols="1, 4"]
|===
|Nutzer        |
Ein vom Admin autorisierter Mitarbeiterin bzw. eine autorisierte Mitarbeiterin,
der oder die sich im System ab- und anmelden kann.

|Mitarbeiter   |
Eine Mitarbeiterin bzw. ein Mitarbeiter der Firma. Dies kann ein Angestellter oder der Filialleiter sein.

|Admin         |
Hier wird angenommen, das dies der Filialleiter ist, der dann die höchsten Rechte im System hat.
Er übernimmt daher alle Verwaltungsaufgaben.
Diese Aufgabe kann aber natürlich auch ausgelagert werden.

|Salespoint    |
Java-basiertes Anwendungs-Framework zur Entwicklung von PoS-Anwendungen (Point of Sales)
mit Spring Framework und Spring Boot.
Es besteht aus einer Vielzahl von Geschäftsmodulen, die es den Benutzern ermöglichen,
anspruchsvolle Webanwendungen zu implementieren.

|Ressourcen     |
Ressourcen sind Mitarbeiter, Material und Räume.

|Bestellung     |
Die Bestellung ist ein einzelner Auftrag, den ein Kunde am Annahmeschalter aufgegeben hat.Jeder Auftrag gehört zu einer Dienstleistung und ist mit dem abgegebenen Gegenstand verbunden. Wenn der Auftrag gerade bearbeitet wird, ist ihm ein Mitarbeiter und ein Raum zugeordnet.

|Service        |
Ist eine Dienstleistung mit einen Namen, einen Preis und gehört zu einer Kategorie.

|Time Table     |
Jeder Raum hat einen Zeit-Plan, in dem feste Slots für jeden Tag sind. Die zu bearbeitenden Aufträge werden in die Slots eingeschrieben.

|Finanzmanagement      |
verwaltet alle Einnahmen und Ausgaben. Zudem erlaubt es die akkumulierten Bilanzen aufzuzeigen.

|===

////
== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
////
