= Protokoll Gruppe 24

Treffen am 1.1.2019

Ort:      APB E0005 +
Beginn:   15:01 Uhr +
Ende:     16:10 Uhr

__Schriftführer: Tobias Köllner__

*Nächstes Treffen:* +
8.11.2019, 14:55 Uhr

__Teilnehmer:__

- Anna Lopatkina
- Till Große
- Tobias Köllner
- Kien Dang Tran
- Viktor Reusch


== Aktueller Stand
- Videoshop: Kien, Viktor und Tobias haben Feature implementiert


== Bis Nächste Woche
Pflichtenheft

UMl-Diagramme hinzufügen

Stakeholder: ok

Muss-Kriterien: ein wenig mehr

Kann-kriterien: mehr

Nicht funktionale Anforderung: mehr

gui-prototyp: passt

Dialoglandkarte: nicht relevant

Anwendungsfälle: text fixen

Datenmodell: passt

Akzeptanztestfälle: meeeehr

Produktnutzung: passt

Systemgrenze: Text raus

Glossar:


== To Do
- Großer Prototyp(erste Funktionen)
- Aufteilung der Aufgabenbereiche
- Testplan/DevDoc
- Salespoint anschauen


Viktor:  ist relativ fertig

Anna: Videoshop-Prototyp

Till: Weiß was er zu tun hat

Tobias: Videoshopprototyp fixen/ Teil des Pflichtenhefts hinzufügen(Akteure für UseCases/Stakeholder)

Kien: Fliestext Aufgabenstellung und Zielsetzung
